// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa1_89e2fC3yfmPvfIAxSadDxwPJQPnRU',
    appId: '1:938880910478:web:f97a0cc7d9d8e7414bb5df',
    messagingSenderId: '938880910478',
    projectId: 'clevertap-android-and-flutter',
    authDomain: 'clevertap-android-and-flutter.firebaseapp.com',
    databaseURL: 'https://clevertap-android-and-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'clevertap-android-and-flutter.appspot.com',
    measurementId: 'G-EFQVGFHTYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSSEXiJD4OBNs2CX7xtkLmfppPfcJQbbM',
    appId: '1:938880910478:android:67a6e990d4c571cf4bb5df',
    messagingSenderId: '938880910478',
    projectId: 'clevertap-android-and-flutter',
    databaseURL: 'https://clevertap-android-and-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'clevertap-android-and-flutter.appspot.com',
  );
}
